# Generated by Django 4.0.6 on 2022-08-09 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interests',
            name='interest',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.DecimalField(decimal_places=0, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='sociallinks',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='sociallinks',
            name='fb',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='sociallinks',
            name='insta',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='sociallinks',
            name='linkdin',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='sociallinks',
            name='website',
            field=models.URLField(null=True),
        ),
    ]
